[project]
org-name= "wso2"
version= "0.1.0"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "ftp"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["ftp_listener"]

[dependencies]

