[project]
org-name= "wso2"
version= "0.1.1"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "uploadtoftp"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["uploadtoftp"]

[dependencies]
