[project]
org-name= "wso2"
version= "0.1.1"
license= ["Apache-2.0"]
authors= ["WSO2"]
keywords= ["ballerina", "integrator", "appointment_service"]
repository= "https://github.com/wso2/ballerina-integrator"
templates= ["appointment_service"]

[dependencies]
