baseURL = "http://example.org/"
languageCode = "en-us"
title = "Ballerina Integrator"

# Theme name
theme = "wso2-learn"

# For search functionality
[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
# Author of the site, will be used in meta information
author = "wso2"
# Shows a check mark for visited pages on the menu
showVisitedLinks = true